### ISSUE TITLE
服务器忙，然后就闪退了（genymotion Android 4.1.1）

### ISSUE THREAD

**Issue by tsdking** [zhujian1989/gank.io#1]
03-29 12:55:29.657 1166-1166/com.jzhu.io.gank E/AndroidRuntime: FATAL EXCEPTION: main
                                                                java.lang.NullPointerException
                                                                    at axf.a(Unknown Source)
                                                                    at ayp.fillData(Unknown Source)
                                                                    at cn.bingoogolapple.androidcommon.adapter.BGARecyclerViewAdapter.onBindViewHolder(Unknown Source)
                                                                    at cn.bingoogolapple.androidcommon.adapter.BGARecyclerViewAdapter.onBindViewHolder(Unknown Source)
                                                                    at agx.onBindViewHolder(Unknown Source)
                                                                    at agx.bindViewHolder(Unknown Source)
                                                                    at ahn.a(Unknown Source)
                                                                    at ahn.b(Unknown Source)
                                                                    at aga.a(Unknown Source)
                                                                    at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
                                                                    at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
                                                                    at android.support.v7.widget.LinearLayoutManager.c(Unknown Source)
                                                                    at android.support.v7.widget.RecyclerView.E(Unknown Source)
                                                                    at android.support.v7.widget.RecyclerView.A(Unknown Source)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.support.v4.view.ViewPager.onLayout(Unknown Source)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                    at android.view.View.layout(View.java:13754)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                    at android.os.Handler.handleCallback(Handler.java:615)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:55

**Comment by zhujian1989** [comment]
谢谢您，我genmotion下载了nexus4.1.1的版本，断网，并没有复现该问题！我稍后会在测试下！
